branches:
  only:
    - master
    - devel
    - feature/clang-tidy-format

language: cpp
#cache: ccache
sudo: required

#see https://apt.llvm.org/
matrix:
  include:
    - name: "clang-format"
      compiler: clang++-9
      addons:
        apt:
          sources:
            - [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-8']
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages: [ 'clang-9', 'clang-tools-9', 'clang-tidy-9', 'clang-format-9', 'colordiff']
      env:
        - MATRIX_ENV="export CXX=clang++-9 CC=clang-9"

before_install:
install:
before_script:
  # we need this only to create the compilation databse for clang tidy
  # - eval "${MATRIX_ENV}"
  # - mkdir build && cd build || exit 1
  # - cmake ..
  # - cd ..
script:
  - export ARANGODB_CLANG_FORMAT_VERSION=9.0.0
  - ./utils/clang-format-check

after_suceess:
after_failure:
after_script:

#notifications:
#  slack:
#    secure: JrnDfdroyURrS85HIVsI4xw82taol+lvOJxduxz4T8mQuckaE3ECRYcxX7MzLJfjpeSLST5kttUiZBckHdZ/pnmraZlQ+1/b1VE6k5hFzkbeM0ShjXKTxHdudXaJKuENunMxDAjVWaBaTTh/iy8ZZbKUYQtWLtLfw3xa5zCKVaQ=
#    on_success: change
#    on_failure: always
