branches:
  only:
    - master
    - devel
    - feature/clang-tidy-format

language: cpp
#cache: ccache
sudo: required

#see https://apt.llvm.org/
matrix:
  include:
    - name: "clang-format"
      compiler: g++
      addons:
        apt:
          sources:
            - [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-8']
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages: [ 'clang-9', 'clang-tools-9', 'clang-tidy-9' ]
      env:
        - MATRIX_ENV="export CXX=clang++-9 CC=clang-9"

before_install:
  #  - wget https://apt.llvm.org/llvm.sh
  #- chmod +x llvm.sh
  #- sudo ./llvm.sh 9 || sudo apt-get install -f -y clang-9 lldb-9 lld-9 clangd-9 llvm-9-tools
  - dpkg -l | grep clang

install:
before_script:
  - eval "${MATRIX_ENV}"
  - mkdir build && cd build || exit 1
  - cmake ..
  - cd ..
script:
  - sudo apt-get install apt-file
  - sudo apt-file update
  - apt-file show clang-9
  - apt-file show clang-tools-9
  - export ARANGODB_CLANG_FORMAT_VERSION=9.0.0
  - ./utils/clang-format-check

after_suceess:
after_failure: 
after_script: 

#notifications:
#  slack:
#    secure: JrnDfdroyURrS85HIVsI4xw82taol+lvOJxduxz4T8mQuckaE3ECRYcxX7MzLJfjpeSLST5kttUiZBckHdZ/pnmraZlQ+1/b1VE6k5hFzkbeM0ShjXKTxHdudXaJKuENunMxDAjVWaBaTTh/iy8ZZbKUYQtWLtLfw3xa5zCKVaQ=
#    on_success: change
#    on_failure: always
