branches:
  only:
    - master
    - devel
    - feature/clang-tidy-format

language: cpp
cache: ccache
sudo: required

matrix:
  include:
    - name: "clang-format"
      compiler: g++
      addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test

        packages:
          - clang-8
          - clang-tools-8
          - clang-tidy-8

before_install:
install:
before_script: 
script:
after_suceess:
after_failure: 
after_script: 

#notifications:
#  slack:
#    secure: JrnDfdroyURrS85HIVsI4xw82taol+lvOJxduxz4T8mQuckaE3ECRYcxX7MzLJfjpeSLST5kttUiZBckHdZ/pnmraZlQ+1/b1VE6k5hFzkbeM0ShjXKTxHdudXaJKuENunMxDAjVWaBaTTh/iy8ZZbKUYQtWLtLfw3xa5zCKVaQ=
#    on_success: change
#    on_failure: always
