branches:
  only:
    - master
    - devel
    - feature/clang-tidy-format

language: cpp
#cache: ccache
sudo: required

matrix:
  include:
    - name: "clang-format"
      compiler: g++
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-6']
          packages: [ 'clang-6', 'clang-tools-6', 'clang-tidy-6' ]
      env:
        - MATRIX_ENV="export CXX=clang++-6 CC=clang-6"

before_install:
install:
before_script:
  - eval "${MATRIX_ENV}"
  - mkdir build && cd build || exit 1
  - cmake ..
  - cd ..
script:
  - exort ARANGODB_CLANG_FORMAT_VERSION=6.0.0
  - ./utils/clang-format-check

after_suceess:
after_failure: 
after_script: 

#notifications:
#  slack:
#    secure: JrnDfdroyURrS85HIVsI4xw82taol+lvOJxduxz4T8mQuckaE3ECRYcxX7MzLJfjpeSLST5kttUiZBckHdZ/pnmraZlQ+1/b1VE6k5hFzkbeM0ShjXKTxHdudXaJKuENunMxDAjVWaBaTTh/iy8ZZbKUYQtWLtLfw3xa5zCKVaQ=
#    on_success: change
#    on_failure: always
